version: '2.1'
services:

  mongo:
    build: mongodb
    hostname: mongo
    ports:
      - 27017:27017
      - 28017:28017
    healthcheck:
      test: mongo localhost:27017/example --eval "db.katalog.count()" 2>&1 | grep -q "MongoDB shell version"
      interval: 10s
      timeout: 10s
      retries: 15

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.0.0.0/24
              ip_range: 10.0.0.0/24
